# Begin of info for dependecy svn-http://sbe-documentationsystem.googlecode.com/svn/tags/rel_2_0_0
list(APPEND OverallDependencies "svn-http://sbe-documentationsystem.googlecode.com/svn/tags/rel_2_0_0")
list(REMOVE_DUPLICATES OverallDependencies)
set(svn-http://sbe-documentationsystem.googlecode.com/svn/tags/rel_2_0_0_Name "DocumentationSystem")
set(svn-http://sbe-documentationsystem.googlecode.com/svn/tags/rel_2_0_0_Type "Project")
set(svn-http://sbe-documentationsystem.googlecode.com/svn/tags/rel_2_0_0_Version "2.0.0")
set(svn-http://sbe-documentationsystem.googlecode.com/svn/tags/rel_2_0_0_ScmPath "http://sbe-documentationsystem.googlecode.com/svn/tags/rel_2_0_0")
set(svn-http://sbe-documentationsystem.googlecode.com/svn/tags/rel_2_0_0_ScmType "svn")
set(svn-http://sbe-documentationsystem.googlecode.com/svn/tags/rel_2_0_0_DependenciesDescription "")
list(APPEND svn-http://sbe-documentationsystem.googlecode.com/svn/tags/rel_2_0_0_DependenciesDescription "DEPENDENCY")
list(APPEND svn-http://sbe-documentationsystem.googlecode.com/svn/tags/rel_2_0_0_DependenciesDescription "URL")
list(APPEND svn-http://sbe-documentationsystem.googlecode.com/svn/tags/rel_2_0_0_DependenciesDescription "http://sbe-documentlibrary.googlecode.com/svn/tags/rel_2_0_0")
list(APPEND svn-http://sbe-documentationsystem.googlecode.com/svn/tags/rel_2_0_0_DependenciesDescription "DEPENDENCY")
list(APPEND svn-http://sbe-documentationsystem.googlecode.com/svn/tags/rel_2_0_0_DependenciesDescription "URL")
list(APPEND svn-http://sbe-documentationsystem.googlecode.com/svn/tags/rel_2_0_0_DependenciesDescription "http://sbe-printerlibrary.googlecode.com/svn/tags/rel_1_0_0")
set(svn-http://sbe-documentationsystem.googlecode.com/svn/tags/rel_2_0_0_Dependencies "")
list(APPEND svn-http://sbe-documentationsystem.googlecode.com/svn/tags/rel_2_0_0_Dependencies "svn-http://sbe-documentlibrary.googlecode.com/svn/tags/rel_2_0_0")
list(APPEND svn-http://sbe-documentationsystem.googlecode.com/svn/tags/rel_2_0_0_Dependencies "svn-http://sbe-printerlibrary.googlecode.com/svn/tags/rel_1_0_0")
set(svn-http://sbe-documentationsystem.googlecode.com/svn/tags/rel_2_0_0_IsExported "yes")
# End of info for dependecy svn-http://sbe-documentationsystem.googlecode.com/svn/tags/rel_2_0_0
# Begin of info for dependecy svn-http://sbe-documentlibrary.googlecode.com/svn/tags/rel_2_0_0
list(APPEND OverallDependencies "svn-http://sbe-documentlibrary.googlecode.com/svn/tags/rel_2_0_0")
list(REMOVE_DUPLICATES OverallDependencies)
set(svn-http://sbe-documentlibrary.googlecode.com/svn/tags/rel_2_0_0_Name "DocumentLibrary")
set(svn-http://sbe-documentlibrary.googlecode.com/svn/tags/rel_2_0_0_Type "Library")
set(svn-http://sbe-documentlibrary.googlecode.com/svn/tags/rel_2_0_0_Version "2.0.0")
set(svn-http://sbe-documentlibrary.googlecode.com/svn/tags/rel_2_0_0_ScmPath "http://sbe-documentlibrary.googlecode.com/svn/tags/rel_2_0_0")
set(svn-http://sbe-documentlibrary.googlecode.com/svn/tags/rel_2_0_0_ScmType "svn")
set(svn-http://sbe-documentlibrary.googlecode.com/svn/tags/rel_2_0_0_DependenciesDescription "")
list(APPEND svn-http://sbe-documentlibrary.googlecode.com/svn/tags/rel_2_0_0_DependenciesDescription "DEPENDENCY")
list(APPEND svn-http://sbe-documentlibrary.googlecode.com/svn/tags/rel_2_0_0_DependenciesDescription "URL")
list(APPEND svn-http://sbe-documentlibrary.googlecode.com/svn/tags/rel_2_0_0_DependenciesDescription "http://sbe-printerlibrary.googlecode.com/svn/tags/rel_1_0_0")
set(svn-http://sbe-documentlibrary.googlecode.com/svn/tags/rel_2_0_0_Dependencies "")
list(APPEND svn-http://sbe-documentlibrary.googlecode.com/svn/tags/rel_2_0_0_Dependencies "svn-http://sbe-printerlibrary.googlecode.com/svn/tags/rel_1_0_0")
set(svn-http://sbe-documentlibrary.googlecode.com/svn/tags/rel_2_0_0_IsExported "yes")
# End of info for dependecy svn-http://sbe-documentlibrary.googlecode.com/svn/tags/rel_2_0_0
# Begin of info for dependecy svn-http://sbe-printerlibrary.googlecode.com/svn/tags/rel_1_0_0
list(APPEND OverallDependencies "svn-http://sbe-printerlibrary.googlecode.com/svn/tags/rel_1_0_0")
list(REMOVE_DUPLICATES OverallDependencies)
set(svn-http://sbe-printerlibrary.googlecode.com/svn/tags/rel_1_0_0_Name "PrinterLibrary")
set(svn-http://sbe-printerlibrary.googlecode.com/svn/tags/rel_1_0_0_Type "Library")
set(svn-http://sbe-printerlibrary.googlecode.com/svn/tags/rel_1_0_0_Version "1.0.0")
set(svn-http://sbe-printerlibrary.googlecode.com/svn/tags/rel_1_0_0_ScmPath "http://sbe-printerlibrary.googlecode.com/svn/tags/rel_1_0_0")
set(svn-http://sbe-printerlibrary.googlecode.com/svn/tags/rel_1_0_0_ScmType "svn")
set(svn-http://sbe-printerlibrary.googlecode.com/svn/tags/rel_1_0_0_DependenciesDescription "")
set(svn-http://sbe-printerlibrary.googlecode.com/svn/tags/rel_1_0_0_Dependencies "")
set(svn-http://sbe-printerlibrary.googlecode.com/svn/tags/rel_1_0_0_IsExported "yes")
# End of info for dependecy svn-http://sbe-printerlibrary.googlecode.com/svn/tags/rel_1_0_0
# Begin of info for dependecy svn-http://sbe-cpputestlibrary.googlecode.com/svn/tags/rel_1_0_0
list(APPEND OverallDependencies "svn-http://sbe-cpputestlibrary.googlecode.com/svn/tags/rel_1_0_0")
list(REMOVE_DUPLICATES OverallDependencies)
set(svn-http://sbe-cpputestlibrary.googlecode.com/svn/tags/rel_1_0_0_Name "CppUTestLibrary")
set(svn-http://sbe-cpputestlibrary.googlecode.com/svn/tags/rel_1_0_0_Type "Unit Test Framework")
set(svn-http://sbe-cpputestlibrary.googlecode.com/svn/tags/rel_1_0_0_Version "1.0.0")
set(svn-http://sbe-cpputestlibrary.googlecode.com/svn/tags/rel_1_0_0_ScmPath "http://sbe-cpputestlibrary.googlecode.com/svn/tags/rel_1_0_0")
set(svn-http://sbe-cpputestlibrary.googlecode.com/svn/tags/rel_1_0_0_ScmType "svn")
set(svn-http://sbe-cpputestlibrary.googlecode.com/svn/tags/rel_1_0_0_DependenciesDescription "")
set(svn-http://sbe-cpputestlibrary.googlecode.com/svn/tags/rel_1_0_0_Dependencies "")
set(svn-http://sbe-cpputestlibrary.googlecode.com/svn/tags/rel_1_0_0_IsExported "yes")
# End of info for dependecy svn-http://sbe-cpputestlibrary.googlecode.com/svn/tags/rel_1_0_0
# Begin of installation order section
set(DEP_INSTALLATION_ORDER "")
list(APPEND DEP_INSTALLATION_ORDER "svn-http://sbe-printerlibrary.googlecode.com/svn/tags/rel_1_0_0")
list(APPEND DEP_INSTALLATION_ORDER "svn-http://sbe-cpputestlibrary.googlecode.com/svn/tags/rel_1_0_0")
list(APPEND DEP_INSTALLATION_ORDER "svn-http://sbe-documentlibrary.googlecode.com/svn/tags/rel_2_0_0")
list(APPEND DEP_INSTALLATION_ORDER "svn-http://sbe-documentationsystem.googlecode.com/svn/tags/rel_2_0_0")
# End of installation order section
# Begin of external dependencies section
list(APPEND EXTERNAL_DEPENDENCIES "svn-http://sbe-cpputestlibrary.googlecode.com/svn/tags/rel_1_0_0")
set(svn-http://sbe-cpputestlibrary.googlecode.com/svn/tags/rel_1_0_0_IsExternal "yes")
# End of external dependencies section
