#!/bin/bash
# printAndExecuteCommand 
#     script prints given argument and execute them
#
#     usage:
#         sbeCheckNewDependencies args

textToPrint=`expr "$*" : '.*/coverityLauncher[[:space:]]*\(.*\)$'`
cmake -E cmake_echo_color --switch=1 --yellow "${textToPrint}"
$*