SET(CMAKE_CXX_FLAGS_DEBUG_INIT "-g -Wall -DDEBUG")
SET(CMAKE_C_FLAGS_DEBUG_INIT "-g -Wall -DDEBUG")

SET(CMAKE_CXX_FLAGS_RELEASE_INIT "-O3 -DNDEBUG -Wall")
SET(CMAKE_C_FLAGS_RELEASE_INIT "-O3 -DNDEBUG -Wall")

SET(CMAKE_CXX_FLAGS_DEBUGWITHCOVERAGE "-g -Wall -DDEBUG -fprofile-arcs -ftest-coverage -pg")
SET(CMAKE_C_FLAGS_DEBUGWITHCOVERAGE "-g -Wall -DDEBUG -fprofile-arcs -ftest-coverage -pg")
